#!/bin/bash

cd gabriel-server-common
git commit -am "Updating protocol"
cd ..
#cd gabriel-android-common
#git commit -am "Updating protocol"
#cd ..
git push --recurse-submodules=check
git commit -am "Updating protocol"
git push
