#!/bin/bash

# Note: I could not get git push --recurse-submodules=check to work
# I chose to just git push each repository individually wrather than wrestle
# with git to try to get this feature working.

cd gabriel-server-common
git commit -am "Updating protocol"
git push
cd ..

cd openrtist
git commit -am "Updating protocol"
cd ..

git commit -am "Updating protocol"
git push
